product:
  type: kmp/lib
  platforms: [jvm, iosX64]

settings:
  <![Warning] Setting `android` doesn't have any effect on platforms `jvm` or `iosX64`. It only applies to `android`!>android<!>:
    <![Warning] Setting `applicationId` cannot be applied to product type `kmp/lib`. Supported product types are: `android/app`!>applicationId<!>: aaa